##Clock signal
set_property PACKAGE_PIN E3 [get_ports CLK_100_i]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_100_i]
create_clock -period 10 -name CLK_100 [get_ports CLK_100_i]

##LEDs
set_property PACKAGE_PIN H5 [get_ports LED4_o]
set_property IOSTANDARD LVCMOS33 [get_ports LED4_o]
set_property PACKAGE_PIN J5 [get_ports LED5_o]
set_property IOSTANDARD LVCMOS33 [get_ports LED5_o]
set_property PACKAGE_PIN T9 [get_ports LED6_o]
set_property IOSTANDARD LVCMOS33 [get_ports LED6_o]
set_property PACKAGE_PIN T10 [get_ports LED7_o]
set_property IOSTANDARD LVCMOS33 [get_ports LED7_o]

set_property PACKAGE_PIN G13 [get_ports EXAMPLE1_i]
set_property IOSTANDARD LVCMOS33 [get_ports EXAMPLE1_i]
set_property PACKAGE_PIN B11 [get_ports EXAMPLE2_i]
set_property IOSTANDARD LVCMOS33 [get_ports EXAMPLE2_i]
set_property PACKAGE_PIN A11 [get_ports EXAMPLE3_i]
set_property IOSTANDARD LVCMOS33 [get_ports EXAMPLE3_i]
set_property PACKAGE_PIN D12 [get_ports EXAMPLE1_o]
set_property IOSTANDARD LVCMOS33 [get_ports EXAMPLE1_o]
set_property PACKAGE_PIN D13 [get_ports EXAMPLE2_o]
set_property IOSTANDARD LVCMOS33 [get_ports EXAMPLE2_o]
set_property PACKAGE_PIN B18 [get_ports EXAMPLE3_o]
set_property IOSTANDARD LVCMOS33 [get_ports EXAMPLE3_o]

set_property PACKAGE_PIN E15 [get_ports FIFO_DIN_i[0]]
set_property IOSTANDARD LVCMOS33 [get_ports FIFO_DIN_i[0]]
set_property PACKAGE_PIN E16 [get_ports FIFO_DIN_i[1]]
set_property IOSTANDARD LVCMOS33 [get_ports FIFO_DIN_i[1]]
set_property PACKAGE_PIN D15 [get_ports FIFO_DIN_i[2]]
set_property IOSTANDARD LVCMOS33 [get_ports FIFO_DIN_i[2]]
set_property PACKAGE_PIN C15 [get_ports FIFO_DIN_i[3]]
set_property IOSTANDARD LVCMOS33 [get_ports FIFO_DIN_i[3]]

set_property PACKAGE_PIN J17 [get_ports FIFO_DOUT_o[0]]
set_property IOSTANDARD LVCMOS33 [get_ports FIFO_DOUT_o[0]]
set_property PACKAGE_PIN J18 [get_ports FIFO_DOUT_o[1]]
set_property IOSTANDARD LVCMOS33 [get_ports FIFO_DOUT_o[1]]
set_property PACKAGE_PIN K15 [get_ports FIFO_DOUT_o[2]]
set_property IOSTANDARD LVCMOS33 [get_ports FIFO_DOUT_o[2]]
set_property PACKAGE_PIN J15 [get_ports FIFO_DOUT_o[3]]
set_property IOSTANDARD LVCMOS33 [get_ports FIFO_DOUT_o[3]]
